kind: pipeline
type: docker
name: account

platform:
  os: linux
  arch: amd64

x-build-docker-image: &x-build-docker-image
  image: plugins/docker
  settings:
    custom_labels:
    - 'BUILD_NUMBER=${DRONE_BUILD_NUMBER}'
    - 'BUILD_SHA=${DRONE_COMMIT_SHA}'
    tags:
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}
      - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

steps:
- name: account-push-registry
  <<: *x-build-docker-image
  settings:
    repo: minghsu0107/sendify-account
    dockerfile: ./account/Dockerfile
    context: ./account
  depends_on:
    - clone
  when:
    event: push
- name: account-update-manifests
  pull: if-not-exists
  image: minghsu0107/update-kustomization:v1.0.3
  environment:
    SSH_KEY:
      from_secret: ssh_key
    IMAGES: minghsu0107/sendify-account
    IMAGE_TAG: ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    MANIFEST_HOST: github.com
    MANIFEST_USER: minghsu0107
    MANIFEST_REPO: sendify-manifests
    MANIFEST_BRANCH: ${DRONE_COMMIT_BRANCH}
    KUSTOMIZATION: staging/account
  depends_on:
    - account-push-registry
  when:
    event: push
trigger:
  branch:
  - main

---
kind: pipeline
type: docker
name: web

platform:
  os: linux
  arch: amd64

x-build-docker-image: &x-build-docker-image
  image: plugins/docker
  settings:
    custom_labels:
    - 'BUILD_NUMBER=${DRONE_BUILD_NUMBER}'
    - 'BUILD_SHA=${DRONE_COMMIT_SHA}'
    tags:
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}
      - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

steps:
- name: client-push-registry
  <<: *x-build-docker-image
  settings:
    repo: minghsu0107/sendify-web-client
    dockerfile: ./web-client/dockerfile
    context: ./web-client
  depends_on:
    - clone
  when:
    event: push
- name: server-push-registry
  <<: *x-build-docker-image
  settings:
    repo: minghsu0107/sendify-web-server
    dockerfile: ./web-server/dockerfile
    context: ./web-server
  depends_on:
    - clone
  when:
    event: push
- name: web-update-manifests
  pull: if-not-exists
  image: minghsu0107/update-kustomization:v1.0.3
  environment:
    SSH_KEY:
      from_secret: ssh_key
    IMAGES: minghsu0107/sendify-web-client,minghsu0107/sendify-web-server
    IMAGE_TAG: ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    MANIFEST_HOST: github.com
    MANIFEST_USER: minghsu0107
    MANIFEST_REPO: sendify-manifests
    MANIFEST_BRANCH: ${DRONE_COMMIT_BRANCH}
    KUSTOMIZATION: staging/web
  depends_on:
    - client-push-registry
    - server-push-registry
  when:
    event: push

---
kind: pipeline
type: docker
name: api-chat

platform:
  os: linux
  arch: amd64

x-build-docker-image: &x-build-docker-image
  image: plugins/docker
  settings:
    custom_labels:
    - 'BUILD_NUMBER=${DRONE_BUILD_NUMBER}'
    - 'BUILD_SHA=${DRONE_COMMIT_SHA}'
    tags:
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}
      - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

steps:
- name: push-registry
  <<: *x-build-docker-image
  settings:
    repo: minghsu0107/sendify-api-chat
    dockerfile: ./api-chat/dockerfile
    context: ./api-chat
  depends_on:
    - clone
  when:
    event: push
- name: update-manifests
  pull: if-not-exists
  image: minghsu0107/update-kustomization:v1.0.3
  environment:
    SSH_KEY:
      from_secret: ssh_key
    IMAGES: minghsu0107/sendify-api-chat
    IMAGE_TAG: ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    MANIFEST_HOST: github.com
    MANIFEST_USER: minghsu0107
    MANIFEST_REPO: sendify-manifests
    MANIFEST_BRANCH: ${DRONE_COMMIT_BRANCH}
    KUSTOMIZATION: staging/api-chat
  depends_on:
    - push-registry
  when:
    event: push

---
kind: pipeline
type: docker
name: api-store

platform:
  os: linux
  arch: amd64

x-build-docker-image: &x-build-docker-image
  image: plugins/docker
  settings:
    custom_labels:
    - 'BUILD_NUMBER=${DRONE_BUILD_NUMBER}'
    - 'BUILD_SHA=${DRONE_COMMIT_SHA}'
    tags:
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}
      - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

steps:
- name: push-registry
  <<: *x-build-docker-image
  settings:
    repo: minghsu0107/sendify-api-store
    dockerfile: ./api-store/Dockerfile
    context: ./api-store
  depends_on:
    - clone
  when:
    event: push
- name: update-manifests
  pull: if-not-exists
  image: minghsu0107/update-kustomization:v1.0.3
  environment:
    SSH_KEY:
      from_secret: ssh_key
    IMAGES: minghsu0107/sendify-api-store
    IMAGE_TAG: ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    MANIFEST_HOST: github.com
    MANIFEST_USER: minghsu0107
    MANIFEST_REPO: sendify-manifests
    MANIFEST_BRANCH: ${DRONE_COMMIT_BRANCH}
    KUSTOMIZATION: staging/api-store
  depends_on:
    - push-registry
  when:
    event: push

---
kind: pipeline
type: docker
name: object

platform:
  os: linux
  arch: amd64

x-build-docker-image: &x-build-docker-image
  image: plugins/docker
  settings:
    custom_labels:
    - 'BUILD_NUMBER=${DRONE_BUILD_NUMBER}'
    - 'BUILD_SHA=${DRONE_COMMIT_SHA}'
    tags:
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}
      - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

steps:
- name: pycodestyle
  image: shyper/pycodestyle
  commands:
    - pycodestyle **/*.py
  when:
    event: pull_request

- name: object-push-registry
  <<: *x-build-docker-image
  settings:
    repo: minghsu0107/sendify-object
    dockerfile: ./object/Dockerfile
    context: ./object
  depends_on:
    - clone
  when:
    event: push