kind: pipeline
type: docker
name: default


platform:
  os: linux
  arch: amd64

services:
- name: mysql
  image: mysql:8.0
  environment:
    MYSQL_USER: ming
    MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: account
  command:
    - mysqld
    - --default-authentication-plugin=mysql_native_password
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    - --lower_case_table_names=1
    - --max_allowed_packet=128M

x-build-docker-image: &x-build-docker-image
  image: plugins/docker
  settings:
    custom_labels:
    - 'BUILD_NUMBER=${DRONE_BUILD_NUMBER}'
    - 'BUILD_SHA=${DRONE_COMMIT_SHA}'
    tags:
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}
      - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

steps:
- name: pingdb
  image: mysql:8.0
  commands:
  - /bin/sh -c 'until mysql -hmysql -uming -ppassword; do echo "Waiting for db..."; sleep 1; done'
- name: test
  pull: if-not-exists
  image: golang:1.15.2
  environment:
    DB_DSN: "ming:password@tcp(mysql:3306)/account?charset=utf8mb4&parseTime=True&loc=Local"
  commands:
  - cd account
  - go mod download
  - make test
  depends_on:
    - pingdb
- name: push-registry
  <<: *x-build-docker-image
  settings:
    repo: minghsu0107/sendify-account
    dockerfile: ./account/Dockerfile
    context: ./account
  depends_on:
    - test
  when:
    event: push
- name: update-manifests
  pull: if-not-exists
  image: line/kubectl-kustomize:1.20.2-3.9.1
  environment:
    SSH_KEY:
      from_secret: ssh_key
    CONTAINER_REPO: minghsu0107/sendify-account
    MANIFEST_HOST: github.com
    MANIFEST_USER: minghsu0107
    MANIFEST_REPO: sendify-manifests
    SVC_PATH: staging/account
  commands:
  - apk update && apk add --no-cache git && apk add --no-cache openssh
  - mkdir -p ~/.ssh && echo $SSH_KEY | base64 -d > ~/.ssh/id_rsa && chmod 700 ~/.ssh/id_rsa && ssh-keyscan $MANIFEST_HOST >> ~/.ssh/known_hosts
  - rm -rf $MANIFEST_REPO && git clone ssh://git@$MANIFEST_HOST/$MANIFEST_USER/$MANIFEST_REPO.git
  - cd $MANIFEST_REPO/$SVC_PATH && kustomize edit set image $CONTAINER_REPO:${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}
  - git add . && git commit -m "update to ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:7}"
  - git push ssh://git@$MANIFEST_HOST/$MANIFEST_USER/$MANIFEST_REPO.git
  depends_on:
    - push-registry
  when:
    event: push
trigger:
  branch:
  - main